name: ci

on:
  push:
    branches:
      - master
      - release/**

  pull_request:

jobs:
  dist:
    name: distribution packages
    timeout-minutes: 10
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          pip install virtualenv
          make aws-lambda-layer-build

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            dist/*
            dist-serverless/*

  docs:
    timeout-minutes: 10
    name: build documentation
    runs-on: ubuntu-16.04

    if: "startsWith(github.ref, 'refs/heads/release/')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          pip install virtualenv
          make apidocs
          cd docs/_build && zip -r gh-pages ./

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: docs/_build/gh-pages.zip

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          pip install tox
          tox -e linters

  test:
    continue-on-error: true
    timeout-minutes: 45
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
          ["3.6"]

    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: sentry
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # Maps tcp port 5432 on service container to the host
        ports:
          - 5432:5432

    env:
      SENTRY_PYTHON_TEST_POSTGRES_USER: postgres
      SENTRY_PYTHON_TEST_POSTGRES_PASSWORD: sentry
      SENTRY_PYTHON_TEST_POSTGRES_NAME: ci_test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup
        env:
          PGHOST: localhost
          PGPASSWORD: sentry
        run: |
          psql -c 'create database travis_ci_test;' -U postgres
          psql -c 'create database test_travis_ci_test;' -U postgres
          pip install codecov tox

      - name: run tests
        env:
          CI_PYTHON_VERSION: ${{ matrix.python-version }}
        timeout-minutes: 45
        run: |
          coverage erase
          ./scripts/runtox.sh '' --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
          coverage combine .coverage*
          coverage xml -i
          codecov --file coverage.xml
          
  test-aarch64:
    name: "Test ${{ matrix.pyver }} aarch64"
    strategy:
      matrix:
        pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
        arch: [aarch64]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_${{ matrix.arch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Install tools
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} ${{ env.py }} -m pip install -U  pip build
    - name: Install dependencies
      run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            ${{ env.img }} \
            bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
            source .env/bin/activate && \
            yum install -y epel-release && \
            yum install -y redis && \
            ps -ef | grep redis && \
            /usr/bin/redis-server /etc/redis.conf --supervised systemd& && \
            ps -ef | grep redis && \
            systemctl start redis && \
            systemctl enable redis && \
            systemctl status redis && \
            deactivate'
  
 
